# Яндекс.Дзен

### Цель исследования

Провести анализ взаимодействия пользователей с карточками Яндекс.Дзен.

### Задачи исследования

- Построить дашборд в соответсвии с ТЗ;
- Ответить на вопросы менеджеров с помощью дашборда;

### Ход исследования
[Импорт данных](#data-import)  
[Техническое задание](#draft)    
[Результаты](#result)

## Импорт данных<a class="anchor" id="data-import"></a>

In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine

In [2]:
db_config = {'user': '---', # имя пользователя
            'pwd': '---', # пароль
            'host': '---',
            'port': ---, # порт подключения
            'db': '---'} # название базы данных

connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(db_config['user'],
                                                db_config['pwd'],
                                                db_config['host'],
                                                db_config['port'],
                                                db_config['db'])

engine = create_engine(connection_string)

In [3]:
query = '''
            SELECT * FROM dash_visits
        '''

In [4]:
visits = pd.io.sql.read_sql(query, con = engine)
visits

,record_id,item_topic,source_topic,age_segment,dt,visits
0,1040597,Деньги,Авто,18-25,2019-09-24 18:32:00,3
1,1040598,Деньги,Авто,18-25,2019-09-24 18:35:00,1
2,1040599,Деньги,Авто,18-25,2019-09-24 18:54:00,4
3,1040600,Деньги,Авто,18-25,2019-09-24 18:55:00,17
4,1040601,Деньги,Авто,18-25,2019-09-24 18:56:00,27
...,...,...,...,...,...,...
30740,1071337,Юмор,Финансы,36-40,2019-09-24 18:57:00,2
30741,1071338,Юмор,Финансы,36-40,2019-09-24 19:00:00,1
30742,1071339,Юмор,Финансы,41-45,2019-09-24 18:54:00,1
30743,1071340,Юмор,Финансы,41-45,2019-09-24 18:56:00,1
30744,1071341,Юмор,Финансы,41-45,2019-09-24 19:00:00,1

In [5]:
visits.to_csv('dash_visits.csv')

## Техническое задание<a class="anchor" id="draft"></a>

- Бизнес-задача: анализ взаимодействия пользователей с карточками Яндекс.Дзен;
- Насколько часто предполагается пользоваться дашбордом: не реже, чем раз в неделю;
- Кто будет основным пользователем дашборда: менеджеры по анализу контента;
- Состав данных для дашборда:
    - История событий по темам карточек (два графика - абсолютные числа и процентное соотношение);
    - Разбивка событий по темам источников;
    - Таблица соответствия тем источников темам карточек;
- По каким параметрам данные должны группироваться:
    - Дата и время;
    - Тема карточки;
    - Возрастная группа;
- Характер данных:
    - История событий по темам карточек — абсолютные величины с разбивкой по минутам;
    - Разбивка событий по темам источников — относительные величины (% событий);
    - Соответствия тем источников темам карточек - абсолютные величины;
- Важность: все графики имеют равную важность;
- Источники данных для дашборда: cырые данные о событиях взаимодействия пользователей с карточками;
- База данных, в которой будут храниться агрегированные данные: дополнительные агрегированные таблицы в БД zen;
- Частота обновления данных: один раз в сутки, в полночь по UTC;
- Макет дашборда:  
![title](draft.png)

## Результаты<a class="anchor" id="result"></a>

#### Материалы:
[Презентация](https://disk.yandex.ru/i/pPxy-lpL1FIS8g)  
[Дашборд](https://public.tableau.com/views/ZEN_16589526825330/zen_dashboard)

#### Как много карточек генерируют источники с разными темами?
- Больше всего карточек генерируют источники по "общечеловеческим темам”: отношения, советы, путешествия;
- Абсолютный лидер во взаимодействию: источник путешествия и карточка рассказы. Трэвел-блоги в топе.

#### Как соотносятся темы карточек и темы источников?
- Наиболее популярные источники и карточки тематически взаимосвязаны. Например: политика и общество популярное сочетание, а женская психология и строительство — нет. Возможно это связано с тем как расставляются теги;
- Есть явные лидеры среди источников которые генерируют карточки почти во всем темам, например семейные отношения, путешествия, полезные советы;